version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shop-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: shop
    ports:
      - "5432:5432"                
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: 
        context: .
        dockerfile: Dockerfile.bot
    container_name: shop-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_LINK_ASYNC=${DB_LINK_ASYNC}
      - DB_LINK=${DB_LINK}
    depends_on:
      - db

  admin:
    build: 
      context: .
      dockerfile: Dockerfile.admin
    container_name: shop-admin
    restart: unless-stopped
    environment:
      - DB_LINK_ASYNC=${DB_LINK_ASYNC}
      - DB_LINK=${DB_LINK}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: shop-nginx
    ports:
      - "8080:80"   # http://localhost:8080/admin
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - admin

volumes:
  postgres_data: